<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="4" assertions="4" errors="1" warnings="0" failures="0" skipped="0" time="0.113361">
    <testsuite name="App" tests="4" assertions="4" errors="1" warnings="0" failures="0" skipped="0" time="0.113361">
      <testsuite name="ExampleSessionTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\session\ExampleSessionTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.040980">
        <testcase name="testSessionSimple" class="ExampleSessionTest" classname="ExampleSessionTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\session\ExampleSessionTest.php" line="11" assertions="1" time="0.040980"/>
      </testsuite>
      <testsuite name="AuthTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\unit\AuthTest.php" tests="1" assertions="0" errors="1" warnings="0" failures="0" skipped="0" time="0.064202">
        <testcase name="testLogin" class="AuthTest" classname="AuthTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\unit\AuthTest.php" line="16" assertions="0" time="0.064202">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">AuthTest::testLogin
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.&#13;
Main connection [SQLite3]: Class 'SQLite3' not found

C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\Database\BaseConnection.php:407
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\Database\BaseConnection.php:577
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\Database\BaseBuilder.php:1455
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\Model.php:210
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\BaseModel.php:622
C:\Users\Viper\Documents\GitHub\oss-conta-api\app\Models\UsersModel.php:60
C:\Users\Viper\Documents\GitHub\oss-conta-api\app\Models\UsersModel.php:77
C:\Users\Viper\Documents\GitHub\oss-conta-api\app\Controllers\AuthController.php:57
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\CodeIgniter.php:825
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\CodeIgniter.php:412
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\CodeIgniter.php:320
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\Test\FeatureTestTrait.php:188
C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\codeigniter4\framework\system\Test\FeatureTestTrait.php:235
C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\unit\AuthTest.php:19
phpvfscomposer://C:\Users\Viper\Documents\GitHub\oss-conta-api\vendor\phpunit\phpunit\phpunit:97</error>
        </testcase>
      </testsuite>
      <testsuite name="HealthTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\unit\HealthTest.php" tests="2" assertions="3" errors="0" warnings="0" failures="0" skipped="0" time="0.008179">
        <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\unit\HealthTest.php" line="13" assertions="1" time="0.003595"/>
        <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="C:\Users\Viper\Documents\GitHub\oss-conta-api\tests\unit\HealthTest.php" line="18" assertions="2" time="0.004584"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
